# Allow larger file uploads (if needed)
client_max_body_size 100M;

# Serve media files from your disk
location /media {
    alias /app/media;
}

# Serve static files (CSS, JS)
location /static {
    alias /usr/src/app/staticfiles;
}

# Route all other traffic to your Django app
location / {
    try_files /dev/null @django_app;
}

# Block access to SQLite files (security)
location ~\.sqlite3$ {
    deny all;
    error_page 403 =404 /;
}

# Allow Let's Encrypt / well-known (if needed)
location ~ /\.well-known {
    allow all;
}