# Generated by Django 6.0.6 on 2026-06-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_deal_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
