# Generated by Django 6.0.6 on 2026-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_last_deal_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notification_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
