# Generated by Django 6.0.6 on 2026-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='final_offer_used',
            field=models.BooleanField(default=False),
        ),
    ]
