# Generated by Django 6.0.6 on 2026-06-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_final_offer_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='final_offer_used',
            new_name='special_offer_used',
        ),
    ]
