# Generated by Django 6.0.6 on 2026-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_final_offer_used_customer_special_offer_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
