# Generated by Django 6.0.6 on 2026-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_is_verified_customer_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp_created_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
