# Generated by Django 6.0.6 on 2026-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_customer_is_verified_remove_customer_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shadow_banned',
            field=models.BooleanField(default=False),
        ),
    ]
