# Generated by Django 6.0.6 on 2026-08-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
