# Generated by Django 6.0.6 on 2026-08-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_store_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydeal',
            name='has_revealed',
            field=models.BooleanField(default=False),
        ),
    ]
