# Generated by Django 6.0.6 on 2026-08-05 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dailydeal_has_revealed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'پول نقد'), ('bank', 'انتقال بانکی'), ('card', 'کارت به کارت'), ('online', 'پرداخت آنلاین')], default='card', max_length=50)),
                ('subscription_start', models.DateTimeField()),
                ('subscription_end', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.store')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
