# Generated by Django 6.0.6 on 2026-08-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent_given',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
