# Generated by Django 6.0.6 on 2026-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customer_consent_given_customer_consent_given_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydeal',
            name='auto_revealed',
            field=models.BooleanField(default=False),
        ),
    ]
