# Generated by Django 6.0.6 on 2026-08-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dailydeal_auto_revealed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.CreateModel(
            name='ProductMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_main', to='core.store')),
            ],
            options={
                'unique_together': {('store', 'product_code')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.productmain'),
        ),
    ]
